### PR TITLE
Fix return values

### PR DESCRIPTION
**Pull request by pjam**
Adjusted the return value on methods savePriceProductForProductConcrete and savePriceProductForProductAbstract.

We should get the values from the entities and not from the result of the save operation.

### CODE REVIEW

**Comment by namikk** [comment]
I just encountered this issue in my project and can confirm that the changes here fix it. Would be great to have it merged soon.

**Comment by tvaleriy** [comment]
Hi @pjam,
thank you for your contribution into Spryker and sorry that I haven't noticed this PR earlier. And thank you @namikk that you popped it up.
I will create an internal ticket out of this PR so our development team could import this PR from this repo to our meno-repo where we are developing. You will remain as the author of the PR though. Then this change will be released by our release application. Internal ticket is in a queue and will be processed as soon as possible.

Best,
Spryker Support Team

**Comment by pjam** [comment]
> Hi @pjam,
> thank you for your contribution into Spryker and sorry that I haven't noticed this PR earlier. And thank you @namikk that you popped it up.
> I will create an internal ticket out of this PR so our development team could import this PR from this repo to our meno-repo where we are developing. You will remain as the author of the PR though. Then this change will be released by our release application. Internal ticket is in a queue and will be processed as soon as possible.
> 
> Best,
> Spryker Support Team

Thanks :+1: 
And thanks to @namikk for giving it visibility :wink:

**Comment by pjam** [comment]
bump

**Comment by tvaleriy** [comment]
Hi @pjam, sorry for the delay here, internal ticket is waiting to be QAed. Hopefully this will be done this week.

Best,
Spryker Support Team

**Comment by tvaleriy** [comment]
Hi @pjam, @namikk,
this should have been released in https://github.com/spryker/price-product/releases/tag/4.18.1.
Thank you for commiting into Spryker!

I'll close this PR.

Best,
Spryker Support Team

**Pull request closed without merging**
